global:
  scrape_interval: 15s 

remote_write: 
  - url: http://promscale:9201/write

remote_read: 
  - url: http://promscale:9201/read


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']